In [1]:
import numpy as np

In [2]:
a = [1,2,3]
b = [4,5,6]
type(a)

list

In [3]:
a + b

[1, 2, 3, 4, 5, 6]

In [6]:
c = np.array(a)
d = np.array(b)
c

array([1, 2, 3])

In [5]:
type(c)

numpy.ndarray

In [7]:
c

array([1, 2, 3])

In [8]:
d

array([4, 5, 6])

In [9]:
c + d

array([5, 7, 9])

In [11]:
a * 4

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [13]:
c * 4

array([ 4,  8, 12])

In [14]:
c

array([1, 2, 3])

In [15]:
c[2]

3

In [16]:
c.append(5)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [17]:
c

array([1, 2, 3])

In [20]:
c.dtype # attribute

dtype('int64')

In [21]:
c.shape

(3,)

In [22]:
c_np = np.array([[1,2,3], [4,5,6]])
c_np

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
c_np.shape

(2, 3)

In [25]:
c_np.size

6

In [26]:
len(c_np)

2

In [28]:
list(range(1, 100, 10))

[1, 11, 21, 31, 41, 51, 61, 71, 81, 91]

In [29]:
np.arange(1, 100, 10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [32]:
np.linspace(1, 100, 11)

array([  1. ,  10.9,  20.8,  30.7,  40.6,  50.5,  60.4,  70.3,  80.2,
        90.1, 100. ])

In [37]:
np.random.randint(1, 100)

96

In [38]:
np.random.randint(1, 100, 5)

array([48, 26, 32, 15, 56])

In [47]:
np.random.seed(42)
e = np.random.randint(1, 100, (3, 4))
e

array([[52, 93, 15, 72],
       [61, 21, 83, 87],
       [75, 75, 88, 24]])

In [48]:
e.reshape(2, 6)

array([[52, 93, 15, 72, 61, 21],
       [83, 87, 75, 75, 88, 24]])

In [49]:
e.reshape(6, 2)

array([[52, 93],
       [15, 72],
       [61, 21],
       [83, 87],
       [75, 75],
       [88, 24]])

In [50]:
e.reshape(12, 1)

array([[52],
       [93],
       [15],
       [72],
       [61],
       [21],
       [83],
       [87],
       [75],
       [75],
       [88],
       [24]])

In [51]:
e.reshape(1, 12)

array([[52, 93, 15, 72, 61, 21, 83, 87, 75, 75, 88, 24]])

In [52]:
e.reshape(2, 4)

ValueError: cannot reshape array of size 12 into shape (2,4)

In [53]:
e.reshape(4, -1)

array([[52, 93, 15],
       [72, 61, 21],
       [83, 87, 75],
       [75, 88, 24]])

In [54]:
e.reshape(6, -1)

array([[52, 93],
       [15, 72],
       [61, 21],
       [83, 87],
       [75, 75],
       [88, 24]])

In [55]:
e.reshape(-1, 2)

array([[52, 93],
       [15, 72],
       [61, 21],
       [83, 87],
       [75, 75],
       [88, 24]])

In [57]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [59]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [63]:
np.ones((4,3)) * 2

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [64]:
e

array([[52, 93, 15, 72],
       [61, 21, 83, 87],
       [75, 75, 88, 24]])

In [65]:
e > 50

array([[ True,  True, False,  True],
       [ True, False,  True,  True],
       [ True,  True,  True, False]])