In [1]:
import numpy as np
import matplotlib.pyplot as plt
import time

In [3]:
a = 3
b = 5
temp = a
a = b
b = temp
print(a, b)

5 3


In [2]:
def swapValues(arr, i, j):
    temp = arr[i]
    arr[i] = arr[j]
    arr[j] = temp

In [3]:
def SelectionSort(arr):
    for i in range(0, len(arr)-1):
        minIndex = i
        for j in range(i+1, len(arr)):
            if arr[j] < arr[minIndex]:
                minIndex = j
        swapValues(arr, i, minIndex)

In [17]:
np.random.seed(42)
myArr = np.random.randint(1, 100, 10)
print("Unsorted:", myArr)
SelectionSort(myArr)
print("Sorted:", myArr)

Unsorted: [52 93 15 72 61 21 83 87 75 75]
Sorted: [15 21 52 61 72 75 75 83 87 93]


In [20]:
n = 10000
np.random.seed(42)
myArr = np.random.randint(1, 1000000, n)

start = time.time()
SelectionSort(myArr)
end = time.time()
diff = end - start
print("Selection Sort takes", diff, "seconds when n is", n)

n = 20000
np.random.seed(42)
myArr = np.random.randint(1, 1000000, n)

start = time.time()
SelectionSort(myArr)
end = time.time()
diff = end - start
print("Selection Sort takes", diff, "seconds when n is", n)

Selection Sort takes 4.669983148574829 seconds when n is 10000
Selection Sort takes 18.167916774749756 seconds when n is 20000


In [4]:
def BubbleSort(arr):
    for i in range(0, len(arr)-1):
        for j in range(0, len(arr)-i-1):
            if arr[j] > arr[j+1]:
                swapValues(arr, j, j+1)

In [5]:
def ModifiedBubbleSort(arr):
    for i in range(0, len(arr)-1):
        isOrdered = True
        for j in range(0, len(arr)-i-1):
            if arr[j] > arr[j+1]:
                swapValues(arr, j, j+1)
                isOrdered = False
        if isOrdered:
            break

In [22]:
np.random.seed(42)
myArr = np.random.randint(1, 100, 10)
print("Unsorted:", myArr)
BubbleSort(myArr)
print("Sorted:", myArr)

Unsorted: [52 93 15 72 61 21 83 87 75 75]
Sorted: [15 21 52 61 72 75 75 83 87 93]


In [23]:
n = 10000
np.random.seed(42)
myArr = np.random.randint(1, 1000000, n)

start = time.time()
BubbleSort(myArr)
end = time.time()
diff = end - start
print("BubbleSort takes", diff, "seconds when n is", n)

n = 20000
np.random.seed(42)
myArr = np.random.randint(1, 1000000, n)

start = time.time()
BubbleSort(myArr)
end = time.time()
diff = end - start
print("BubbleSort takes", diff, "seconds when n is", n)

BubbleSort takes 9.267621755599976 seconds when n is 10000
BubbleSort takes 35.653671979904175 seconds when n is 20000


In [25]:
n = 10000
np.random.seed(42)
myArr = np.random.randint(1, 1000000, n)

start = time.time()
BubbleSort(myArr)
end = time.time()
diff = end - start
print("BubbleSort takes", diff, "seconds when n is", n)


n = 10000
np.random.seed(42)
myArr = np.random.randint(1, 1000000, n)

start = time.time()
ModifiedBubbleSort(myArr)
end = time.time()
diff = end - start
print("Modified BubbleSort takes", diff, "seconds when n is", n)

BubbleSort takes 9.187855243682861 seconds when n is 10000
Modified BubbleSort takes 9.284433841705322 seconds when n is 10000


In [26]:
n = 10000
myArr = np.arange(1, n)

start = time.time()
BubbleSort(myArr)
end = time.time()
diff = end - start
print("BubbleSort takes", diff, "seconds when n is", n)


n = 10000
myArr = np.arange(1, n)

start = time.time()
ModifiedBubbleSort(myArr)
end = time.time()
diff = end - start
print("Modified BubbleSort takes", diff, "seconds when n is", n)

BubbleSort takes 4.857100963592529 seconds when n is 10000
Modified BubbleSort takes 0.0009660720825195312 seconds when n is 10000


In [6]:
def MergeTwoSortedLists(list1, list2): # O(m + n)
    newSortedList = []
    idx1, idx2 = 0, 0
    while idx1 < len(list1) and idx2 < len(list2):
        if list1[idx1] < list2[idx2]:
            newSortedList.append(list1[idx1])
            idx1 += 1
        else:
            newSortedList.append(list2[idx2])
            idx2 += 1
    
    while idx1 < len(list1):
        newSortedList.append(list1[idx1])
        idx1 += 1
    
    while idx2 < len(list2):
        newSortedList.append(list2[idx2])
        idx2 += 1
    
    return newSortedList

In [31]:
MergeTwoSortedLists([1,5,8], [7,9, 10, 11])

[1, 5, 7, 8, 9, 10, 11]

In [7]:
def MergeSort(arr):
    if len(arr) == 1:
        return arr
    middleIndex = len(arr) // 2
    unsorted_left = arr[:middleIndex]
    unsorted_right = arr[middleIndex:]
    sorted_left = MergeSort(unsorted_left)
    sorted_right = MergeSort(unsorted_right)
    sorted_list = MergeTwoSortedLists(sorted_left, sorted_right)
    return sorted_list

In [8]:
np.random.seed(42)
myArr = np.random.randint(1, 100, 10)
print("Unsorted:", myArr)
myArr = MergeSort(myArr)
print("Sorted:", myArr)

Unsorted: [52 93 15 72 61 21 83 87 75 75]
Sorted: [15, 21, 52, 61, 72, 75, 75, 83, 87, 93]


In [9]:
def QuickSort(arr, i, j):
    if i < j:
        pivot_idx = np.random.randint(i, j+1)
        swapValues(arr, pivot_idx, j)
        left, right = i, j-1
        while left <= right:
            while arr[left] <= arr[j] and left <= right:
                left += 1
            while arr[right] >= arr[j] and left <= right:
                right -= 1
            if left < right:
                swapValues(arr, left, right)
        swapValues(arr, left, j)
        QuickSort(arr, i, left-1)
        QuickSort(arr, left+1, j)

In [53]:
np.random.seed(42)
myArr = np.random.randint(1, 100, 10)
print("Unsorted:", myArr)
QuickSort(myArr, 0, len(myArr)-1)
print("Sorted:", myArr)

Unsorted: [52 93 15 72 61 21 83 87 75 75]
Sorted: [15 21 52 61 72 75 75 83 87 93]


In [10]:
np.random.seed(42)
myArr = np.random.randint(1, 100, 10)
myArr

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75])

In [12]:
sorted_array = sorted(myArr)
sorted_array

[15, 21, 52, 61, 72, 75, 75, 83, 87, 93]

In [13]:
myArr

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75])

In [ ]:
myArr.sort() # PowerSort() -> O(n logn)
myArr

array([15, 21, 52, 61, 72, 75, 75, 83, 87, 93])

In [16]:
np.random.seed(42)
myArr = np.random.randint(1, 100, 10)
myArr

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75])

In [ ]:
def findPairWithSmallestDiff(myList): # O(n^2)
    num1, num2 = myList[0], myList[1] # assumig there are at least 2 values in the list
    minDiff = abs(num1 - num2)
    for i in range(len(myList)-1): # n
        for j in range(i+1, len(myList)): # n-1
            curDiff = abs(myList[i]-myList[j])
            if curDiff < minDiff:
                minDiff = curDiff
                num1, num2 = myList[i], myList[j]
    
    print(num1, num2)

In [18]:
findPairWithSmallestDiff(myArr)

75 75


In [ ]:
def findPairWithSmallestDiff_v2(myList): # O(n logn) + O(n) -> O(n logn)
    #myList.sort()
    myList = sorted(myList) # O(n logn)
    num1, num2 = myList[0], myList[1] # assumig there are at least 2 values in the list
    minDiff = abs(num1 - num2)
    for i in range(1, len(myList)-1): # O(n)
        curDiff = myList[i+1] - myList[i]
        if curDiff < minDiff:
            minDiff = curDiff
            num1, num2 = myList[i], myList[i+1]
    print(num1, num2)

In [20]:
findPairWithSmallestDiff_v2(myArr)

75 75


In [23]:
myList = [1,5,2,4] # 3 is missing here

In [ ]:
def FindMissingNumber(myList): # O(n^2)
    n = len(myList) # O(1)
    for val in range(1, n+2): # O(n)
        if val not in myList: # O(n)
            return val

In [ ]:
def FindMissingNumberv2(myList): # O(n logn) + O(n) -> O(n logn)
    myList = sorted(myList) # O(n logn)

    for i in range(len(myList)-1): # O(n)
        diff = myList[i+1] - myList[i]
        if diff > 1:
            return myList[i] + 1

In [ ]:
def FindMissingNumberv3(myList): # O(n)
    n = len(myList) + 1 # expected greatest number in the list -> O(1)
    expectedSum = n * (n+1) / 2 # O(1)
    return expectedSum - sum(myList) # O(n)

In [24]:
FindMissingNumber(myList)

3

In [26]:
FindMissingNumberv2(myList)

3

In [28]:
FindMissingNumberv3(myList)

3.0

In [ ]:
def FindMissingNumber2ndVersion(myList): # [1,4,4,4,2] -> O(n) + O(n) -> O(n)
    mySet = set(myList) # O(n) -> {1, 4, 2}
    length = len(mySet) # O(1)
    for val in range(1, length + 2): # O(n)
        if val not in mySet: # O(1)
            return val
    

In [30]:
FindMissingNumber2ndVersion([1,4,4,4,2])

3

In [36]:
def FindClosestPair(myList, target):
    myList = sorted(myList)

    left, right = 0, len(myList)-1
    minDiff = abs(target - (myList[right]+myList[left]))
    num1, num2 = myList[left], myList[right]
    
    while left < right:
        curDiff = abs(target - (myList[right]+myList[left]))
        if curDiff < minDiff:
            minDiff = curDiff
            num1, num2 = myList[left], myList[right]
        if curDiff == 0:
            return num1, num2
        elif myList[right]+myList[left] < target:
            left += 1
        else:
            right -= 1
    return num1, num2

In [37]:
FindClosestPair([22, 10, 28, 29, 30, 40], 54)

(22, 30)